max_steps = 100

[model]
seq_len = 4096
name = "Qwen/Qwen3.5-9B"

[model.lora]
rank = 16

[data]
type = "sft"
name = "/home/ubuntu/sft_1k"
micro_batch_size = 8
seq_len = 4096
batch_size = 32

[optim]
lr = 1e-4

[ckpt]
interval = 50
