"""Regenerates catan_llm/geometry.py from the engine's base map."""

from pathlib import Path

from catanatron import Color, Game, RandomPlayer

HEADER = '"""Static base-map topology. Generated by scripts/gen_geometry.py."""'


def main():
    game = Game([RandomPlayer(Color.RED), RandomPlayer(Color.BLUE)], seed=0)
    adjacent = game.state.board.map.adjacent_tiles
    node_tiles = {
        node: sorted(tile.id for tile in tiles)
        for node, tiles in sorted(adjacent.items())
    }
    edges = sorted(
        {
            tuple(sorted(edge))
            for tile in game.state.board.map.land_tiles.values()
            for edge in tile.edges.values()
        }
    )
    lines = [HEADER, "", "NODE_TILES = {"]
    lines += [f"    {node}: {tiles}," for node, tiles in node_tiles.items()]
    lines += ["}", "", "NODE_EDGES = ["]
    lines += [f"    {edge}," for edge in edges]
    lines += ["]", ""]
    Path("catan_llm/geometry.py").write_text("\n".join(lines))
    print(f"catan_llm/geometry.py: {len(node_tiles)} nodes, {len(edges)} edges")


if __name__ == "__main__":
    main()
