"""Regenerates catan_llm/geometry.py from the engine's base map."""

from pathlib import Path

from catanatron import Color, Game, RandomPlayer

HEADER = '"""Static base-map topology. Generated by scripts/gen_geometry.py."""'


def main():
    game = Game([RandomPlayer(Color.RED), RandomPlayer(Color.BLUE)], seed=0)
    adjacent = game.state.board.map.adjacent_tiles
    node_tiles = {
        node: sorted(tile.id for tile in tiles)
        for node, tiles in sorted(adjacent.items())
    }
    lines = [HEADER, "", "NODE_TILES = {"]
    lines += [f"    {node}: {tiles}," for node, tiles in node_tiles.items()]
    lines += ["}", ""]
    Path("catan_llm/geometry.py").write_text("\n".join(lines))
    print(f"catan_llm/geometry.py: {len(node_tiles)} nodes")


if __name__ == "__main__":
    main()
