"""Regenerates catan_llm/geometry.py and viewer geometry from the engine's base map."""

import json
from pathlib import Path

from catanatron import Color, Game, RandomPlayer

HEADER = '"""Static base-map topology. Generated by scripts/gen_geometry.py."""'
SQRT3 = 3**0.5
CORNERS = {
    "NORTH": (0.0, -1.0),
    "NORTHEAST": (SQRT3 / 2, -0.5),
    "SOUTHEAST": (SQRT3 / 2, 0.5),
    "SOUTH": (0.0, 1.0),
    "SOUTHWEST": (-SQRT3 / 2, 0.5),
    "NORTHWEST": (-SQRT3 / 2, -0.5),
}


def tile_center(coordinate):
    q, r = coordinate[0], coordinate[2]
    return (SQRT3 * q + SQRT3 / 2 * r, 1.5 * r)


def main():
    game = Game([RandomPlayer(Color.RED), RandomPlayer(Color.BLUE)], seed=0)
    board_map = game.state.board.map
    node_tiles = {
        node: sorted(tile.id for tile in tiles)
        for node, tiles in sorted(board_map.adjacent_tiles.items())
    }
    edges = sorted(
        {
            tuple(sorted(edge))
            for tile in board_map.land_tiles.values()
            for edge in tile.edges.values()
        }
    )
    tile_xy = {}
    node_xy = {}
    for coordinate, tile in board_map.land_tiles.items():
        cx, cy = tile_center(coordinate)
        tile_xy[tile.id] = (round(cx, 4), round(cy, 4))
        for ref, node in tile.nodes.items():
            dx, dy = CORNERS[ref.name]
            node_xy[node] = (round(cx + dx, 4), round(cy + dy, 4))
    water_xy = sorted(
        tile_center(coordinate)
        for coordinate, tile in board_map.tiles.items()
        if tile.__class__.__name__ in ("Water", "Port")
    )
    water_xy = [(round(x, 4), round(y, 4)) for x, y in water_xy]

    lines = [HEADER, "", "NODE_TILES = {"]
    lines += [f"    {node}: {tiles}," for node, tiles in node_tiles.items()]
    lines += ["}", "", "NODE_EDGES = ["]
    lines += [f"    {edge}," for edge in edges]
    lines += ["]", "", "TILE_XY = {"]
    lines += [f"    {tile}: {xy}," for tile, xy in sorted(tile_xy.items())]
    lines += ["}", "", "NODE_XY = {"]
    lines += [f"    {node}: {xy}," for node, xy in sorted(node_xy.items())]
    lines += ["}", "", "WATER_XY = ["]
    lines += [f"    {xy}," for xy in water_xy]
    lines += ["]", ""]
    Path("catan_llm/geometry.py").write_text("\n".join(lines))
    print(f"catan_llm/geometry.py: {len(node_xy)} nodes, {len(edges)} edges")

    viewer = Path("viewer/replay.html")
    if viewer.exists():
        geo = {
            "tiles": {str(k): list(v) for k, v in sorted(tile_xy.items())},
            "nodes": {str(k): list(v) for k, v in sorted(node_xy.items())},
            "water": [list(xy) for xy in water_xy],
        }
        text = viewer.read_text()
        begin, end = "/* GEO:BEGIN */", "/* GEO:END */"
        head, rest = text.split(begin)
        _, tail = rest.split(end)
        block = f"{begin}\nconst GEO = {json.dumps(geo)};\n{end}"
        viewer.write_text(head + block + tail)
        print("viewer/replay.html: geometry injected")


if __name__ == "__main__":
    main()
